name: trading_bot_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - numpy
  - pip
  - pip:
    - python-dotenv
    - ipykernel
    - alpaca-trade-api
    - alpaca-py
    - toml
    - matplotlib
    - tqdm
    - scipy
    - numba
    - line_profiler
    - snakeviz
    - seaborn